// Builds the static web export for Cloudflare Pages.
//
// `expo export --platform web` writes dynamic routes as literal files named
// after the segment — dist/location/[id].html — so a request for
// /location/<uuid> matches nothing and 404s. Rewriting straight at the bracket
// file doesn't work either: Pages strips `.html` and 308-redirects to the
// extensionless path, and the encoded bracket form redirects too, which ends in
// a loop. Copying each dynamic page to a plain filename and rewriting there
// serves the correct prerendered HTML with no redirect and no home-page flash.
//
// Verified against `wrangler pages dev`: the response for /location/<uuid> is
// byte-identical to dist/location/[id].html.

import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(appRoot, 'dist');

// Each dynamic route: the exported bracket file, and the plain name to serve it
// under. Add a line here whenever a new dynamic route is introduced.
const DYNAMIC_ROUTES = [
  { urlPrefix: '/location', exported: 'location/[id].html', servedAs: 'location/detail.html' },
  { urlPrefix: '/lists', exported: 'lists/[id].html', servedAs: 'lists/detail.html' },
];

console.log('> expo export --platform web');
execFileSync('npx', ['expo', 'export', '--platform', 'web'], {
  cwd: appRoot,
  stdio: 'inherit',
  shell: process.platform === 'win32',
});

const rules = [];
for (const route of DYNAMIC_ROUTES) {
  const from = join(dist, route.exported);
  if (!existsSync(from)) {
    // A renamed or removed route would otherwise fail silently at runtime.
    throw new Error(
      `Expected ${route.exported} in the export but it is missing. ` +
        `Update DYNAMIC_ROUTES in scripts/build-web.mjs.`
    );
  }
  copyFileSync(from, join(dist, route.servedAs));
  rules.push(`${route.urlPrefix}/*  /${route.servedAs.replace(/\.html$/, '')}  200`);
}

writeFileSync(
  join(dist, '_redirects'),
  `# Generated by scripts/build-web.mjs — do not edit by hand.\n${rules.join('\n')}\n`
);

// Cloudflare's "404-page" handling looks for 404.html; Expo Router names its
// not-found page +not-found.html. Copy it so an unknown URL lands on the app's
// own page instead of a bare Cloudflare error.
const notFound = join(dist, '+not-found.html');
if (existsSync(notFound)) {
  copyFileSync(notFound, join(dist, '404.html'));
  console.log('> copied +not-found.html to 404.html');
} else {
  console.warn('! +not-found.html missing — unknown URLs will show a bare 404');
}

console.log(`\n> wrote dist/_redirects:\n${rules.map((r) => `    ${r}`).join('\n')}`);
console.log('\nStatic site ready in dist/');
