// Builds the static web export for Cloudflare Pages.
//
// `expo export --platform web` writes dynamic routes as literal files named
// after the segment — dist/location/[id].html — so a request for
// /location/<uuid> matches nothing and 404s. Rewriting straight at the bracket
// file doesn't work either: Pages strips `.html` and 308-redirects to the
// extensionless path, and the encoded bracket form redirects too, which ends in
// a loop. Copying each dynamic page to a plain filename and rewriting there
// serves the correct prerendered HTML with no redirect and no home-page flash.
//
// Verified against `wrangler pages dev`: the response for /location/<uuid> is
// byte-identical to dist/location/[id].html.

import { execFileSync, execSync } from 'node:child_process';
import { copyFileSync, existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(appRoot, 'dist');

// Each dynamic route: the exported bracket file, and the plain name to serve it
// under. Add a line here whenever a new dynamic route is introduced.
const DYNAMIC_ROUTES = [
  { urlPrefix: '/location', exported: 'location/[id].html', servedAs: 'location/detail.html' },
  { urlPrefix: '/lists', exported: 'lists/[id].html', servedAs: 'lists/detail.html' },
];

console.log('> expo export --platform web');
// Windows needs a shell (Node won't spawn a .cmd directly since CVE-2024-27980),
// but an args array plus `shell: true` is deprecated — DEP0190 — because Node
// concatenates them unescaped. One command string for Windows, no shell at all
// anywhere else. Same treatment as scripts/publish-update.mjs.
if (process.platform === 'win32') {
  execSync('npx.cmd expo export --platform web', { cwd: appRoot, stdio: 'inherit' });
} else {
  execFileSync('npx', ['expo', 'export', '--platform', 'web'], { cwd: appRoot, stdio: 'inherit' });
}

const rules = [];
for (const route of DYNAMIC_ROUTES) {
  const from = join(dist, route.exported);
  if (!existsSync(from)) {
    // A renamed or removed route would otherwise fail silently at runtime.
    throw new Error(
      `Expected ${route.exported} in the export but it is missing. ` +
        `Update DYNAMIC_ROUTES in scripts/build-web.mjs.`
    );
  }
  copyFileSync(from, join(dist, route.servedAs));
  rules.push(`${route.urlPrefix}/*  /${route.servedAs.replace(/\.html$/, '')}  200`);
}

// The loop above catches a route that was renamed or removed. It cannot catch a
// route that was *added*, and that failure is the quiet one: the page exports
// fine, nothing errors, and /profile/<id> just 404s in production for as long as
// nobody happens to try it. So walk the export and insist every bracket file is
// accounted for.
function bracketFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) return bracketFiles(full);
    return entry.isFile() && entry.name.includes('[') && entry.name.endsWith('.html') ? [full] : [];
  });
}

const declared = new Set(DYNAMIC_ROUTES.map((r) => r.exported.replace(/\//g, '\\')));
const unhandled = bracketFiles(dist)
  .map((f) => relative(dist, f))
  .filter((f) => !declared.has(f) && !declared.has(f.replace(/\\/g, '/')));

if (unhandled.length > 0) {
  throw new Error(
    `Dynamic route(s) exported but not served: ${unhandled.join(', ')}.\n` +
      `Add an entry to DYNAMIC_ROUTES in scripts/build-web.mjs, or these URLs will 404 ` +
      `in production with no other symptom.`
  );
}

writeFileSync(
  join(dist, '_redirects'),
  `# Generated by scripts/build-web.mjs — do not edit by hand.\n${rules.join('\n')}\n`
);

// Android verifies the app's claim on locastar.se/auth/* by fetching this file
// over https. Expo copies public/ into dist/ for us, but if that ever stops
// happening the only symptom is auth links quietly opening the browser again
// instead of the app — so check rather than hope.
const assetLinks = join(dist, '.well-known', 'assetlinks.json');
if (!existsSync(assetLinks)) {
  throw new Error(
    'dist/.well-known/assetlinks.json is missing. Android App Links verification ' +
      'will fail and auth email links will open the browser instead of the app. ' +
      'Check that apps/mobile/public/.well-known/assetlinks.json still exists.'
  );
}
console.log('> .well-known/assetlinks.json present');

// The iOS half of the same claim. Apple fetches this file directly and will not
// accept it unless it is served as application/json — which is what public/_headers
// is for, since the file deliberately has no extension. Same failure mode as
// above: auth links quietly open Safari and nothing is logged.
const aasa = join(dist, '.well-known', 'apple-app-site-association');
if (!existsSync(aasa)) {
  throw new Error(
    'dist/.well-known/apple-app-site-association is missing. iOS universal links ' +
      'will fail and auth email links will open Safari instead of the app. ' +
      'Check that apps/mobile/public/.well-known/apple-app-site-association still exists.'
  );
}
if (!existsSync(join(dist, '_headers'))) {
  throw new Error(
    'dist/_headers is missing, so apple-app-site-association will be served with ' +
      'the wrong content type and Apple will reject it. Check apps/mobile/public/_headers.'
  );
}
console.log('> .well-known/apple-app-site-association present, _headers present');

// Cloudflare's "404-page" handling looks for 404.html; Expo Router names its
// not-found page +not-found.html. Copy it so an unknown URL lands on the app's
// own page instead of a bare Cloudflare error.
const notFound = join(dist, '+not-found.html');
if (existsSync(notFound)) {
  copyFileSync(notFound, join(dist, '404.html'));
  console.log('> copied +not-found.html to 404.html');
} else {
  console.warn('! +not-found.html missing — unknown URLs will show a bare 404');
}

console.log(`\n> wrote dist/_redirects:\n${rules.map((r) => `    ${r}`).join('\n')}`);
console.log('\nStatic site ready in dist/');
