/*
 * Category names in both languages, keyed by the slug in the `categories`
 * table.
 *
 * Lives here for the same reason CategoryColors does: both the app and the
 * website render these, and they are keyed by database data. The website needs
 * the Swedish names the app already has — retyping 54 of them would guarantee
 * they drift.
 *
 * The app merges this into its i18next resources under `categories`, so every
 * existing `t("categories.<slug>")` call keeps working unchanged.
 */

export const CATEGORY_NAMES: Record<"en" | "sv", Record<string, string>> = {
  en: {
    "4h-farms": "4H Farms",
    "action-parks": "Action parks",
    "amerikan-fotball": "American Football",
    "archery-ranges": "Archery Ranges",
    "baseball": "Baseball",
    "basketball": "Basketball",
    "beaches": "Beaches",
    "bike-trails": "Bike trails",
    "birdwatching": "Birdwatching",
    "bmx": "BMX",
    "boule": "Boule",
    "bowling": "Bowling",
    "camping": "Camping",
    "climbing": "Climbing",
    "cricket": "Cricket",
    "disc-golf-frisbee": "Disc Golf (Frisbee)",
    "diving-spots": "Diving spots",
    "dog-parks": "Dog parks",
    "festival": "Festivals",
    "fishing": "Fishing",
    "football": "Soccer",
    "golf": "Golf",
    "grill-sites": "Grill sites",
    "gyms-outside": "Gyms (outdoor)",
    "hiking": "Hiking Trails",
    "historical-ruins-places": "Historical Ruins/Places",
    "horse-track": "Horse track",
    "ice-skating": "Ice skating",
    "jogging-trails": "Jogging Trails",
    "library": "Library",
    "mini-golf": "Mini Golf",
    "motocross-atv-tracks": "Motocross/ATV tracks",
    "museums-free": "Museums (Free)",
    "nature-reserves": "Nature reserves",
    "obstacle-course": "Obstacle course",
    "other": "Others",
    "outdoor": "Outdoor recreation area",
    "paintball": "Paintball",
    "parkour": "Parkour",
    "picknick-parks": "Picnic parks",
    "playgrounds": "Playgrounds",
    "public-art": "Public art",
    "race-tracks-vehicle": "Race tracks (Vehicle)",
    "rc-race-track": "RC Race track",
    "roads": "Roads",
    "scenic-place": "Scenic Place",
    "shooting-range": "Shooting range",
    "skatepark": "Skatepark",
    "skiing": "Ski slope",
    "swimming": "Pools (Outdoors)",
    "tennis": "Tennis",
    "track-and-field-stadium": "Track & Field Stadium",
    "volleyball": "Volleyball",
    "water-activities": "Water activities",
  },
  sv: {
    "4h-farms": "4H-gårdar",
    "action-parks": "Äventyrsparker",
    "amerikan-fotball": "Amerikansk fotboll",
    "archery-ranges": "Bågskyttebanor",
    "baseball": "Baseboll",
    "basketball": "Basket",
    "beaches": "Stränder",
    "bike-trails": "Cykelleder",
    "birdwatching": "Fågelskådning",
    "bmx": "BMX",
    "boule": "Boule",
    "bowling": "Bowling",
    "camping": "Camping",
    "climbing": "Klättring",
    "cricket": "Cricket",
    "disc-golf-frisbee": "Discgolf",
    "diving-spots": "Dykplatser",
    "dog-parks": "Hundrastgårdar",
    "festival": "Festivaler",
    "fishing": "Fiske",
    "football": "Fotboll",
    "golf": "Golf",
    "grill-sites": "Grillplatser",
    "gyms-outside": "Utegym",
    "hiking": "Vandringsleder",
    "historical-ruins-places": "Historiska ruiner och platser",
    "horse-track": "Ridbana",
    "ice-skating": "Skridskoåkning",
    "jogging-trails": "Motionsspår",
    "library": "Bibliotek",
    "mini-golf": "Minigolf",
    "motocross-atv-tracks": "Motocross- och ATV-banor",
    "museums-free": "Museer (gratis)",
    "nature-reserves": "Naturreservat",
    "obstacle-course": "Hinderbana",
    "other": "Övrigt",
    "outdoor": "Friluftsplats",
    "paintball": "Paintball",
    "parkour": "Parkour",
    "picknick-parks": "Picknickparker",
    "playgrounds": "Lekplatser",
    "public-art": "Offentlig konst",
    "race-tracks-vehicle": "Racerbanor",
    "rc-race-track": "RC-bana",
    "roads": "Vägar",
    "scenic-place": "Utsiktsplats",
    "shooting-range": "Skjutbana",
    "skatepark": "Skatepark",
    "skiing": "Skidbacke",
    "swimming": "Utomhusbad",
    "tennis": "Tennis",
    "track-and-field-stadium": "Friidrottsarena",
    "volleyball": "Volleyboll",
    "water-activities": "Vattenaktiviteter",
  },
};

/** The display name for a slug, falling back to English then to the slug. */
export function categoryName(slug: string | null, language: "en" | "sv"): string | null {
  if (!slug) return null;
  return CATEGORY_NAMES[language][slug] ?? CATEGORY_NAMES.en[slug] ?? null;
}
