/*
 * Pull the website's two faces down from Google and write them into
 * apps/web/public/fonts, with a stylesheet that points at the local copies.
 *
 * Run from the repo root:  node tools/fetch-fonts.mjs
 *
 * Why self-hosted at all: loading them from fonts.googleapis.com is a
 * render-blocking request to a third party that also hands them every
 * visitor's IP address on page load, with no consent step. For a Swedish
 * consumer product that is a question nobody wants to have to answer, and the
 * local copies are faster anyway.
 *
 * Both families are variable fonts, so Google serves one file per subset and
 * varies only the font-weight in the CSS. Downloading per weight fetches the
 * same bytes four times over; this writes one file per subset and declares a
 * weight range, which is also what makes the browser load one file instead of
 * four.
 */
import fs from 'node:fs';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Spline+Sans:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap';

// Chrome's UA, or Google serves the ttf fallback sheet instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

/* Swedish needs latin for åäö and latin-ext for the rest of Europe. Cyrillic,
 * Greek and Vietnamese were being offered to browsers that never ask. */
const SUBSETS = new Set(['latin', 'latin-ext']);

/** The range each family is declared across, since one file covers them all. */
const RANGES = { 'Spline Sans': '300 600', 'JetBrains Mono': '400 500' };

const OUT = path.join('apps', 'web', 'public', 'fonts');

const sheet = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
fs.mkdirSync(OUT, { recursive: true });

const blocks = [...sheet.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];
const seen = new Set();
const faces = [];

for (const [, subset, block] of blocks) {
  if (!SUBSETS.has(subset)) continue;

  const family = block.match(/font-family: '([^']+)'/)[1];
  const key = `${family}|${subset}`;
  if (seen.has(key)) continue;
  seen.add(key);

  const url = block.match(/src: url\((https:[^)]+)\)/)[1];
  const range = block.match(/unicode-range: ([^;]+);/)[1];
  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}.woff2`;

  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  fs.writeFileSync(path.join(OUT, file), Buffer.from(await res.arrayBuffer()));

  faces.push(`/* ${family} — ${subset} */
@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${RANGES[family]};
  font-display: swap;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${range};
}`);
  console.log(`${file}  ${(fs.statSync(path.join(OUT, file)).size / 1024).toFixed(0)}KB`);
}

fs.writeFileSync(
  path.join(OUT, 'fonts.css'),
  `/*
 * Generated by tools/fetch-fonts.mjs — do not edit by hand.
 *
 * One file per family per subset: both faces are variable fonts, so the same
 * bytes cover every weight the site uses.
 */

${faces.join('\n\n')}
`
);
console.log(`\n${faces.length} faces written to ${OUT}`);
